# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/functions.ipynb.

# %% auto 0
__all__ = ['apply_one', 'apply_conditions_and_functions']

# %% ../../nbs/utils/functions.ipynb 1
from typing import List, Callable

# %% ../../nbs/utils/functions.ipynb 3
def apply_one(func, function):
    def wrapped(x):
        return func(function(x))
    return wrapped


def apply_conditions_and_functions(conditions : List[bool], functions : List[Callable]):
    def initial(x):
        return x

    function = initial

    for cond, func in zip(conditions, (functions)):
        if cond:
            function = apply_one(func, function)
    return function



