# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AgentMafia',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/AgentMafia',
                'lib_path': 'agent_mafia'},
  'syms': {'agent_mafia.core': {'agent_mafia.core.foo': ('core.html#foo', 'agent_mafia/core.py')}}}
