# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/agent-mafia',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/agent-mafia',
                'lib_path': 'agent_mafia'},
  'syms': { 'agent_mafia.core': {'agent_mafia.core.foo': ('core.html#foo', 'agent_mafia/core.py')},
            'agent_mafia.utils.files': { 'agent_mafia.utils.files.read_md_from_disk': ( 'utils/files.html#read_md_from_disk',
                                                                                        'agent_mafia/utils/files.py'),
                                         'agent_mafia.utils.files.upsert_folder': ( 'utils/files.html#upsert_folder',
                                                                                    'agent_mafia/utils/files.py')}}}
