"""Default description (change me)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/api.ipynb.

# %% auto 0
__all__ = ['app', 'crawl_url']

# %% ../../nbs/routes/api.ipynb 2
from fastapi import FastAPI, HTTPException

from . import crawler
from ..implementations import scrape_urls

# %% ../../nbs/routes/api.ipynb 3
app = FastAPI()

# %% ../../nbs/routes/api.ipynb 4
@app.post("/api/crawl")
async def crawl_url(
    url: str,
    session_id: str = "default_session",
    export_folder: str = "./export",
    database_table_name: str = "site_pages",
):
    try:
        result = await scrape_urls.process_url(
            url=url,
            source=session_id,
            export_folder=export_folder,
            database_table_name=database_table_name,
            debug_prn=True,
        )

        return {
            "success": True,
            "message": f"Successfully processed {url}",
            "result": result,
        }

    except crawler.Crawler_NotSuccess as e:
        raise HTTPException(
            status_code=500, detail={"error": str(e), "type": "crawler_error"}
        ) from e

    except Exception as e:
        raise HTTPException(
            status_code=500, detail={"error": str(e), "type": "server_error"}
        ) from e
