"""Default description (change me)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/search.ipynb.

# %% auto 0
__all__ = ['tavily_client', 'process_response', 'tavily_search']

# %% ../../nbs/routes/search.ipynb 2
from tavily import TavilyClient, AsyncTavilyClient


# Setup the Tavily Client

# %% ../../nbs/routes/search.ipynb 3
tavily_client = AsyncTavilyClient(api_key=os.environ["TAVILY_API_KEY"])

# %% ../../nbs/routes/search.ipynb 4
def process_response(tavily_response: dict):
    print(tavily_response)
    print(tavily_response.keys())
    # url = tavily_response["url"]
    # content = tavily_response["content"]
    # answer = tavily_response.get("answer")


# Simple Search

# %% ../../nbs/routes/search.ipynb 5
async def tavily_search(
    search_term,
    max_results=3,
    include_raw_content: bool = False,
    include_images: bool = True,
):
    res = await tavily_client.search(
        search_term,
        max_results=max_results,
        include_raw_content=include_raw_content,
        include_images=True,
    )


print(response["results"])
