# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/client/ResponseGetData.ipynb.

# %% auto 0
__all__ = ['ResponseGetData', 'ResponseGetDataOpenAi', 'ResponseGetDataCrawler', 'ResponseGetDataSlack',
           'ResponseGetDataSupabase']

# %% ../../nbs/client/ResponseGetData.ipynb 1
from abc import ABC , abstractmethod
from typing import Any, List
from dataclasses import dataclass, field
from abc import abstractmethod

from slack_bolt.async_app import AsyncApp as AsyncSlackApp
from slack_sdk.web.async_client import AsyncSlackResponse

# %% ../../nbs/client/ResponseGetData.ipynb 3
@dataclass
class ResponseGetData(ABC):
    is_success: bool
    status : int
    response : Any

    @classmethod
    def from_res(abstractmethod):
        pass




# %% ../../nbs/client/ResponseGetData.ipynb 4
@dataclass
class ResponseGetDataOpenAi(ResponseGetData):
    is_success: bool
    status : int
    response : Any
    raw : AsyncSlackResponse = field(default = None, repr = False)

    @classmethod
    def from_res(cls, res: AsyncSlackResponse):
        return cls(
            is_success = True,
            status = 200,
            response = res.choices,
            raw = res
        )

# %% ../../nbs/client/ResponseGetData.ipynb 5
@dataclass
class ResponseGetDataCrawler(ResponseGetData):
    is_success: bool
    status: int
    response: Any
    url: str
    html: Any = field(default=None, repr=False)
    links: List[dict] = field(default_factory=list, repr=False)
    markdown: Any = field(default=None, repr=False)
    raw: Any = field(default=None, repr=False)

    @classmethod
    def from_res(cls, res):
        return cls(
            is_success=res[0].success,
            status=res[0].status_code,
            response=res[0].cleaned_html,
            url=res[0].url,
            html=res[0].html,
            links=res[0].links,
            markdown=res[0].markdown if hasattr(res[0], 'markdown') else None,
            raw=res,
        )

# %% ../../nbs/client/ResponseGetData.ipynb 6
@dataclass
class ResponseGetDataSlack(ResponseGetData):
    is_success: bool
    status : int
    response : Any

    channel_id : str = None
    message_id : float = None
    app : AsyncSlackApp = field(repr = False , default = None)

    @classmethod
    def from_res(cls, res : AsyncSlackResponse, async_app :AsyncSlackApp, **kwargs):
        return cls(
            is_success=res["ok"],
            response=res.data,
            status = res.status_code,
            app = async_app,
            **kwargs
        )

# %% ../../nbs/client/ResponseGetData.ipynb 7
@dataclass
class ResponseGetDataSupabase(ResponseGetData):
    is_success: bool
    status : int
    response : Any
    raw:  Any  = field(repr = False, default = None)

    @classmethod
    def from_res(cls, res ):
        is_success = False

        if res.data:
            is_success= True

        return cls(
            is_success=is_success,
            response=res.data,
            status = 200 if is_success else 400,
            raw  = res
        )
