# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/StreamlineSupabase',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/StreamlineSupabase',
                'lib_path': 'StreamlineSupabase'},
  'syms': {'StreamlineSupabase.core': {'StreamlineSupabase.core.foo': ('core.html#foo', 'StreamlineSupabase/core.py')}}}
